export 'auth/login_screen.dart';
export 'auth/register_screen.dart';
// export 'dashboard/main_screen.dart';
// export 'dashboard/dashboard_screen.dart';
// export 'user/index.dart';
export 'user/edit_screen.dart';
export 'exam/index.dart';
// export 'article/index.dart';
// export 'article/show_screen.dart';
export 'error/error_screen.dart';
